version: '3.8'

services:
    api_node:
        container_name: api_immo_enzo
        restart: unless-stopped
        build: 
            context: ./api_node
        image : api_immo_node:enzo
        command: npm run start
        working_dir: /usr/src/app
        depends_on:
            - db_mongo
        environment: 
            - MONGO_DB=$MONGO_DB
            - MONGO_HOSTNAME=$MONGO_HOSTNAME
            - MONGO_PORT=$MONGO_PORT
            - API_PORT=$API_PORT
        networks:
            default:
                aliases:
                    - $API_HOSTNAME
    db_mongo:
        build: 
            context: ./bdd
        image: immo_db:enzo
        container_name: mongodb_enzo
        restart: unless-stopped
        environment:
            - MONGO_DB=$MONGO_DB
        networks:
            default:
                aliases:
                    - $MONGO_HOSTNAME
    web_site:
        container_name: react_site_enzo
        build:
            context: ./web
        depends_on:
            - reverse_proxy
        image: react_immo:enzo 
        restart: unless-stopped
        environment: 
            - SITE_HOSTNAME=$SITE_HOSTNAME
            - SITE_PORT=$SITE_PORT
        command: /bin/bash -c "envsubst '$$SITE_HOSTNAME $$SITE_PORT'< /etc/nginx/conf.d/server_web.conf.template > /etc/nginx/conf.d/server_web.conf && nginx -g 'daemon off;'"
        networks:
            default:
                aliases:
                    - $SITE_HOSTNAME

    reverse_proxy:
        image: nginx:1.18
        volumes:
            - ./reverse_proxy:/etc/nginx/conf.d
        restart: unless-stopped
        depends_on:
            - api_node
        container_name: reverse_proxy_enzo
        working_dir: /etc/nginx/conf.d
        environment:
            - API_HOSTNAME=$API_HOSTNAME
            - API_PORT=$API_PORT
            - SITE_HOSTNAME=$SITE_HOSTNAME
            - SITE_PORT=$SITE_PORT
            - PROXY_HOSTNAME=$PROXY_HOSTNAME

        ports:
            - $HOST_PORT:80
        command: /bin/bash -c "envsubst < /etc/nginx/conf.d/reverse_proxy.conf.template > /etc/nginx/conf.d/reverse_proxy.conf && nginx -g 'daemon off;'"
